
- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup
    
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd